### ISSUE TITLE
How to adopt the algorithm to point cloud from 16-beams VLP16?

### ISSUE THREAD

**Issue by yunxdai** [lorenwel/linefit_ground_segmentation#35]
Thank you for your excellent work! I am wondering how can I adjust the parameters, or even the algorithm, to make it perform well on point cloud collected by 16 beams LiDAR like VLP-16? I found you mentioned changing `sensor_height` in another issue, is there any additional adjustment to be done, as I found that param change didn't improve the performance?

**Comment by lorenwel** [comment]
Hi @yunxdai,
the parameters should in principle be fairly independent from the number of beams. By far the most important aspect is to get the `sensor_height` correct. 
If you're certain that it is, you could try decreasing `n_bins` or increasing `long_threshold` by a factor of 2, since the lines of the lidar might be a little farther apart from one another.
