### ISSUE TITLE
ground_segmentation_test-2 died for using GPU

### ISSUE THREAD

**Issue by Yws12138** [lorenwel/linefit_ground_segmentation#44]
hi, i have some trouble while using this, it is ok when i using Linux  5.16 without gpu to run the test.launch.
but, when i use Linux 5.10.10-051010-generic with gpu, i got [ground_segmentation_test-2] process has died.
i test the code, found out that the process die at **GroundSegmentation::resetSegments()**, is that ok for you to give me some help?
thank you very much!

**Comment by Yws12138** [comment]
And, i found out that, once visualize turn true, the node will died after counting the cloud points.
If, visualize was false, the program runs fine, and the process can be done.

**Comment by lorenwel** [comment]
Hi @Yws12138,
I assume by "running with GPU", you mean that you use your GPU as a display output instead of your mainboards integrated graphics unit?
Since the algorithm is entirely CPU-based, none if actually runs on GPU. The only part which possibly interacts with the GPU is the visualizer (which you already identified as the trigger of your issue). The visualizer is part of PCL, so it is more likely that the issue relates to the PCL visualizer, rather than my implementation.

Could you please make sure that you can run the [PCL Visualizer demo](https://pcl.readthedocs.io/projects/tutorials/en/latest/pcl_visualizer.html)?
It is entirely possible that there is somehow a mismatch between your driver version and the PCL version you use. Or your graphics driver is generally not set up properly (Especially Nvidia drivers can be tricky). Can you run other programs which do 3D rendering?

Please report back if you can run the PCL Visualizer demo and other 3D programs just fine but the issue persists.

**Comment by lorenwel** [comment]
Please reopen if this issue persists.
