### ISSUE TITLE
Bin/segment indices out of bound

### ISSUE THREAD

**Issue by YoshuaNava** [lorenwel/linefit_ground_segmentation#5]
Hi,
First of all, thank you for sharing your algorithm! I'm currently using it for interfacing ethz-asl/SegMap with a custom LiDAR SLAM pipeline that I developed for my thesis. It has worked great.

When I first tried to use your pkg for segmenting out Velodyne pointclouds, as those from KITTI, I got some issues with the bin and segment indices going out of bound:
https://github.com/lorenwel/linefit_ground_segmentation/blob/11e4ed0090f7637a5929b3c56febe9a6687941ab/linefit_ground_segmentation/src/ground_segmentation.cc#L268

I have submitted a pull request with a patch for this. #4

Kind regards,
Yoshua Nava

**Comment by rdube** [comment]
@YoshuaNava thank you for the contribution! It could be nice to share some results using this ground removal technique on the segmap repo! Cheers!

**Comment by YoshuaNava** [comment]
Hi @rdube 
Thank you!

For sure. I'm submitting the changes I made to the package today. Later today I'll share a video showing the segmentation results I'm getting.

**Comment by rdube** [comment]
@YoshuaNava sounds great!

**Comment by lorenwel** [comment]
Thanks for your bug hunting. 
Do you have information if bin or segment index or both where out of bounds?

Looking at the code, this should happen when a point has `x<0` and `y==0`. Because the std::atan2 function returns values in the range ]-pi, pi] this should lead to an out of bounds index. The segment index should be 0 though. 

Could you test if adding this check instead of yours fixes this issue? This would avoid us having to discard points.

**Comment by YoshuaNava** [comment]
Hi @lorenwel,
I haven't been able to test your suggestion yet. I'm writing my master thesis report now. As soon as I finish I'll do the test.

**Comment by lorenwel** [comment]
#11 should have fixed this
